taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/rachelearl/UVA/ml_container/DS-3022/ds3022-data-project-1/emissions.duckdb'
      database: emissions
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
